stages:
  - qa

repoman:
  stage: qa
  image:
    name: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker run gitlab-registry.hossie.de/docker/repoman .
